# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 57c321ebdf42955843466ce1defe526e62a46ae047d4c51c030bfc3b5c63f70f580de16738ab65e856393db0e57b50cfb364bb926b67e73eb0c375bdb936d782

test:
  secret_key_base: 075c41c0a97091cad57274779e20d8ee688223d830666990634f5190b975f5b0f82a28ef0a112d8653a82079cef624f64a43a6f9a962aa8ab405ffed74c90520

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
